//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarSale.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Car
    {
        public int Id { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Company is required.")]
        public string CompanyName { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Car model is required.")]
        public string CarModel { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Car Year is required.")]
        [Range(1990, 2023, ErrorMessage = "Please enter a year between 1990 to 2023")]
        [RegularExpression(@"^[0-9]{4}$", ErrorMessage = "Invalid year format.")]
        public string Year { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Price is required.")]
        [Range(0, double.MaxValue, ErrorMessage = "Price must be a positive value.")]
        public Nullable<decimal> Price { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Location is required.")]
        public string Location { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Body type is required.")]
        [DataType(DataType.Upload)]
        public string BodyType { get; set; }

        public string addCarMsg { get; set; }
    }
}
